package generate

import "fmt"

// SpecTemplate returns a map with a single entry: the package.yaml spec file.
// For Go services the file lives in <package>_server/package.yaml;
// for C# services it lives at package.yaml in the output root.
func SpecTemplate(data *ServiceData, lang string) map[string]string {
	var path string
	switch lang {
	case "go":
		path = fmt.Sprintf("%s_server/package.yaml", data.PackageName)
	default:
		path = "package.yaml"
	}
	return map[string]string{path: specYAMLTemplate}
}

const specYAMLTemplate = `# Generated by globular-cli; customize as needed.
version: 1

metadata:
  name: {{.PackageName}}

service:
  name: {{.PackageName}}
  exec: {{.PackageName}}_server

steps:
  - id: ensure-user-group
    type: ensure_user_group
    user: globular
    group: globular
    home: "{{stateDir}}"
    shell: /usr/sbin/nologin
    system: true

  - id: ensure-dirs
    type: ensure_dirs
    dirs:
      - path: "{{prefix}}"
        owner: root
        group: root
        mode: 0755
      - path: "{{prefix}}/bin"
        owner: root
        group: root
        mode: 0755

      - path: "{{stateDir}}"
        owner: globular
        group: globular
        mode: 0750
      - path: "{{stateDir}}/services"
        owner: globular
        group: globular
        mode: 0750
      - path: "{{stateDir}}/{{.PackageName}}"
        owner: globular
        group: globular
        mode: 0750

      # TLS directories (certificates must be provisioned by Day-0 bootstrap)
      - path: "{{stateDir}}/pki"
        owner: globular
        group: globular
        mode: 0750

  - id: install-{{.PackageName}}-payload
    type: install_package_payload
    install_bins: true
    install_config: false
    install_spec: false
    install_systemd: false

  - id: ensure-{{.PackageName}}-config
    type: ensure_service_config
    service_name: {{.PackageName}}
    exec: {{.PackageName}}_server
    address_host: auto
    rewrite_if_out_of_range: true

  - id: install-{{.PackageName}}-service
    type: install_services
    units:
      - name: globular-{{.PackageName}}.service
        owner: root
        group: root
        mode: 0644
        atomic: true
        content: |
          [Unit]
          Description=Globular {{.PackageName}}
          After=network-online.target globular-etcd.service
          Wants=network-online.target globular-etcd.service

          [Service]
          Type=simple
          User=globular
          Group=globular
          WorkingDirectory=-{{stateDir}}/{{.PackageName}}
          Environment=GLOBULAR_SERVICES_DIR={{stateDir}}/services
          ExecStart={{prefix}}/bin/{{.PackageName}}_server
          Restart=on-failure
          RestartSec=2
          LimitNOFILE=524288

          [Install]
          WantedBy=multi-user.target

  - id: enable-{{.PackageName}}
    type: enable_services
    services:
      - globular-{{.PackageName}}.service

  - id: start-{{.PackageName}}
    type: start_services
    services:
      - globular-{{.PackageName}}.service
    binaries:
      globular-{{.PackageName}}.service: {{.PackageName}}_server

  - id: health-{{.PackageName}}
    type: health_checks
    services:
      - globular-{{.PackageName}}.service
`
