/**
 * @fileoverview gRPC-Web generated client stub for workflow
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: workflow.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.workflow = require('./workflow_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.workflow.WorkflowServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.workflow.WorkflowServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.StartRunRequest,
 *   !proto.workflow.WorkflowRun>}
 */
const methodDescriptor_WorkflowService_StartRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/StartRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.StartRunRequest,
  proto.workflow.WorkflowRun,
  /**
   * @param {!proto.workflow.StartRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowRun.deserializeBinary
);


/**
 * @param {!proto.workflow.StartRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.WorkflowRun)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowRun>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.startRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/StartRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_StartRun,
      callback);
};


/**
 * @param {!proto.workflow.StartRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.WorkflowRun>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.startRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/StartRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_StartRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.UpdateRunRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_UpdateRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/UpdateRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.UpdateRunRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.UpdateRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.UpdateRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.updateRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/UpdateRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_UpdateRun,
      callback);
};


/**
 * @param {!proto.workflow.UpdateRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.updateRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/UpdateRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_UpdateRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.FinishRunRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_FinishRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/FinishRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.FinishRunRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.FinishRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.FinishRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.finishRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/FinishRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_FinishRun,
      callback);
};


/**
 * @param {!proto.workflow.FinishRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.finishRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/FinishRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_FinishRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.RecordStepRequest,
 *   !proto.workflow.WorkflowStep>}
 */
const methodDescriptor_WorkflowService_RecordStep = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/RecordStep',
  grpc.web.MethodType.UNARY,
  proto.workflow.RecordStepRequest,
  proto.workflow.WorkflowStep,
  /**
   * @param {!proto.workflow.RecordStepRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowStep.deserializeBinary
);


/**
 * @param {!proto.workflow.RecordStepRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.WorkflowStep)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowStep>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.recordStep =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/RecordStep',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_RecordStep,
      callback);
};


/**
 * @param {!proto.workflow.RecordStepRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.WorkflowStep>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.recordStep =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/RecordStep',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_RecordStep);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.UpdateStepRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_UpdateStep = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/UpdateStep',
  grpc.web.MethodType.UNARY,
  proto.workflow.UpdateStepRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.UpdateStepRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.UpdateStepRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.updateStep =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/UpdateStep',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_UpdateStep,
      callback);
};


/**
 * @param {!proto.workflow.UpdateStepRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.updateStep =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/UpdateStep',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_UpdateStep);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.FailStepRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_FailStep = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/FailStep',
  grpc.web.MethodType.UNARY,
  proto.workflow.FailStepRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.FailStepRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.FailStepRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.failStep =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/FailStep',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_FailStep,
      callback);
};


/**
 * @param {!proto.workflow.FailStepRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.failStep =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/FailStep',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_FailStep);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.AddArtifactRefRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_AddArtifactRef = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/AddArtifactRef',
  grpc.web.MethodType.UNARY,
  proto.workflow.AddArtifactRefRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.AddArtifactRefRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.AddArtifactRefRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.addArtifactRef =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/AddArtifactRef',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_AddArtifactRef,
      callback);
};


/**
 * @param {!proto.workflow.AddArtifactRefRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.addArtifactRef =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/AddArtifactRef',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_AddArtifactRef);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.AppendEventRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_AppendEvent = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/AppendEvent',
  grpc.web.MethodType.UNARY,
  proto.workflow.AppendEventRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.AppendEventRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.AppendEventRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.appendEvent =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/AppendEvent',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_AppendEvent,
      callback);
};


/**
 * @param {!proto.workflow.AppendEventRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.appendEvent =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/AppendEvent',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_AppendEvent);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.GetRunRequest,
 *   !proto.workflow.WorkflowRunDetail>}
 */
const methodDescriptor_WorkflowService_GetRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/GetRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.GetRunRequest,
  proto.workflow.WorkflowRunDetail,
  /**
   * @param {!proto.workflow.GetRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowRunDetail.deserializeBinary
);


/**
 * @param {!proto.workflow.GetRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.WorkflowRunDetail)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowRunDetail>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.getRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/GetRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetRun,
      callback);
};


/**
 * @param {!proto.workflow.GetRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.WorkflowRunDetail>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.getRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/GetRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.ListRunsRequest,
 *   !proto.workflow.ListRunsResponse>}
 */
const methodDescriptor_WorkflowService_ListRuns = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/ListRuns',
  grpc.web.MethodType.UNARY,
  proto.workflow.ListRunsRequest,
  proto.workflow.ListRunsResponse,
  /**
   * @param {!proto.workflow.ListRunsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.ListRunsResponse.deserializeBinary
);


/**
 * @param {!proto.workflow.ListRunsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.ListRunsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.ListRunsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.listRuns =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/ListRuns',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_ListRuns,
      callback);
};


/**
 * @param {!proto.workflow.ListRunsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.ListRunsResponse>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.listRuns =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/ListRuns',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_ListRuns);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.GetRunEventsRequest,
 *   !proto.workflow.GetRunEventsResponse>}
 */
const methodDescriptor_WorkflowService_GetRunEvents = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/GetRunEvents',
  grpc.web.MethodType.UNARY,
  proto.workflow.GetRunEventsRequest,
  proto.workflow.GetRunEventsResponse,
  /**
   * @param {!proto.workflow.GetRunEventsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.GetRunEventsResponse.deserializeBinary
);


/**
 * @param {!proto.workflow.GetRunEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.GetRunEventsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.GetRunEventsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.getRunEvents =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/GetRunEvents',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetRunEvents,
      callback);
};


/**
 * @param {!proto.workflow.GetRunEventsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.GetRunEventsResponse>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.getRunEvents =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/GetRunEvents',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetRunEvents);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.GetCurrentRunsForNodeRequest,
 *   !proto.workflow.ListRunsResponse>}
 */
const methodDescriptor_WorkflowService_GetCurrentRunsForNode = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/GetCurrentRunsForNode',
  grpc.web.MethodType.UNARY,
  proto.workflow.GetCurrentRunsForNodeRequest,
  proto.workflow.ListRunsResponse,
  /**
   * @param {!proto.workflow.GetCurrentRunsForNodeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.ListRunsResponse.deserializeBinary
);


/**
 * @param {!proto.workflow.GetCurrentRunsForNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.ListRunsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.ListRunsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.getCurrentRunsForNode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/GetCurrentRunsForNode',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetCurrentRunsForNode,
      callback);
};


/**
 * @param {!proto.workflow.GetCurrentRunsForNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.ListRunsResponse>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.getCurrentRunsForNode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/GetCurrentRunsForNode',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetCurrentRunsForNode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.GetComponentHistoryRequest,
 *   !proto.workflow.ListRunsResponse>}
 */
const methodDescriptor_WorkflowService_GetComponentHistory = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/GetComponentHistory',
  grpc.web.MethodType.UNARY,
  proto.workflow.GetComponentHistoryRequest,
  proto.workflow.ListRunsResponse,
  /**
   * @param {!proto.workflow.GetComponentHistoryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.ListRunsResponse.deserializeBinary
);


/**
 * @param {!proto.workflow.GetComponentHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.ListRunsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.ListRunsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.getComponentHistory =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/GetComponentHistory',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetComponentHistory,
      callback);
};


/**
 * @param {!proto.workflow.GetComponentHistoryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.ListRunsResponse>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.getComponentHistory =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/GetComponentHistory',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetComponentHistory);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.GetWorkflowGraphRequest,
 *   !proto.workflow.WorkflowGraph>}
 */
const methodDescriptor_WorkflowService_GetWorkflowGraph = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/GetWorkflowGraph',
  grpc.web.MethodType.UNARY,
  proto.workflow.GetWorkflowGraphRequest,
  proto.workflow.WorkflowGraph,
  /**
   * @param {!proto.workflow.GetWorkflowGraphRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowGraph.deserializeBinary
);


/**
 * @param {!proto.workflow.GetWorkflowGraphRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.WorkflowGraph)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowGraph>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.getWorkflowGraph =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/GetWorkflowGraph',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetWorkflowGraph,
      callback);
};


/**
 * @param {!proto.workflow.GetWorkflowGraphRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.WorkflowGraph>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.getWorkflowGraph =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/GetWorkflowGraph',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_GetWorkflowGraph);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.WatchRunRequest,
 *   !proto.workflow.WorkflowEventEnvelope>}
 */
const methodDescriptor_WorkflowService_WatchRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/WatchRun',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.workflow.WatchRunRequest,
  proto.workflow.WorkflowEventEnvelope,
  /**
   * @param {!proto.workflow.WatchRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowEventEnvelope.deserializeBinary
);


/**
 * @param {!proto.workflow.WatchRunRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowEventEnvelope>}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.watchRun =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/workflow.WorkflowService/WatchRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_WatchRun);
};


/**
 * @param {!proto.workflow.WatchRunRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowEventEnvelope>}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServicePromiseClient.prototype.watchRun =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/workflow.WorkflowService/WatchRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_WatchRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.WatchNodeRunsRequest,
 *   !proto.workflow.WorkflowEventEnvelope>}
 */
const methodDescriptor_WorkflowService_WatchNodeRuns = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/WatchNodeRuns',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.workflow.WatchNodeRunsRequest,
  proto.workflow.WorkflowEventEnvelope,
  /**
   * @param {!proto.workflow.WatchNodeRunsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowEventEnvelope.deserializeBinary
);


/**
 * @param {!proto.workflow.WatchNodeRunsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowEventEnvelope>}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.watchNodeRuns =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/workflow.WorkflowService/WatchNodeRuns',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_WatchNodeRuns);
};


/**
 * @param {!proto.workflow.WatchNodeRunsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowEventEnvelope>}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServicePromiseClient.prototype.watchNodeRuns =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/workflow.WorkflowService/WatchNodeRuns',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_WatchNodeRuns);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.RetryRunRequest,
 *   !proto.workflow.WorkflowRun>}
 */
const methodDescriptor_WorkflowService_RetryRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/RetryRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.RetryRunRequest,
  proto.workflow.WorkflowRun,
  /**
   * @param {!proto.workflow.RetryRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.WorkflowRun.deserializeBinary
);


/**
 * @param {!proto.workflow.RetryRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.WorkflowRun)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.WorkflowRun>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.retryRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/RetryRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_RetryRun,
      callback);
};


/**
 * @param {!proto.workflow.RetryRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.WorkflowRun>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.retryRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/RetryRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_RetryRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.CancelRunRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_CancelRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/CancelRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.CancelRunRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.CancelRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.CancelRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.cancelRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/CancelRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_CancelRun,
      callback);
};


/**
 * @param {!proto.workflow.CancelRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.cancelRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/CancelRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_CancelRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.AcknowledgeRunRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_WorkflowService_AcknowledgeRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/AcknowledgeRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.AcknowledgeRunRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.workflow.AcknowledgeRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.workflow.AcknowledgeRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.acknowledgeRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/AcknowledgeRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_AcknowledgeRun,
      callback);
};


/**
 * @param {!proto.workflow.AcknowledgeRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.acknowledgeRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/AcknowledgeRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_AcknowledgeRun);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.workflow.DiagnoseRunRequest,
 *   !proto.workflow.DiagnoseRunResponse>}
 */
const methodDescriptor_WorkflowService_DiagnoseRun = new grpc.web.MethodDescriptor(
  '/workflow.WorkflowService/DiagnoseRun',
  grpc.web.MethodType.UNARY,
  proto.workflow.DiagnoseRunRequest,
  proto.workflow.DiagnoseRunResponse,
  /**
   * @param {!proto.workflow.DiagnoseRunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.workflow.DiagnoseRunResponse.deserializeBinary
);


/**
 * @param {!proto.workflow.DiagnoseRunRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.workflow.DiagnoseRunResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.workflow.DiagnoseRunResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.workflow.WorkflowServiceClient.prototype.diagnoseRun =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/workflow.WorkflowService/DiagnoseRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_DiagnoseRun,
      callback);
};


/**
 * @param {!proto.workflow.DiagnoseRunRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.workflow.DiagnoseRunResponse>}
 *     Promise that resolves to the response
 */
proto.workflow.WorkflowServicePromiseClient.prototype.diagnoseRun =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/workflow.WorkflowService/DiagnoseRun',
      request,
      metadata || {},
      methodDescriptor_WorkflowService_DiagnoseRun);
};


module.exports = proto.workflow;

