/**
 * @fileoverview gRPC-Web generated client stub for cluster_controller
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: cluster_controller.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var plan_pb = require('./plan_pb.js')
const proto = {};
proto.cluster_controller = require('./cluster_controller_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cluster_controller.ClusterControllerServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.cluster_controller.ClusterControllerServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Timestamp,
 *   !proto.cluster_controller.ClusterInfo>}
 */
const methodDescriptor_ClusterControllerService_GetClusterInfo = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetClusterInfo',
  grpc.web.MethodType.UNARY,
  google_protobuf_timestamp_pb.Timestamp,
  proto.cluster_controller.ClusterInfo,
  /**
   * @param {!proto.google.protobuf.Timestamp} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ClusterInfo.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Timestamp} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ClusterInfo)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ClusterInfo>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getClusterInfo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetClusterInfo',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetClusterInfo,
      callback);
};


/**
 * @param {!proto.google.protobuf.Timestamp} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ClusterInfo>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getClusterInfo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetClusterInfo',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetClusterInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.CreateJoinTokenRequest,
 *   !proto.cluster_controller.CreateJoinTokenResponse>}
 */
const methodDescriptor_ClusterControllerService_CreateJoinToken = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/CreateJoinToken',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.CreateJoinTokenRequest,
  proto.cluster_controller.CreateJoinTokenResponse,
  /**
   * @param {!proto.cluster_controller.CreateJoinTokenRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.CreateJoinTokenResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.CreateJoinTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.CreateJoinTokenResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.CreateJoinTokenResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.createJoinToken =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/CreateJoinToken',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_CreateJoinToken,
      callback);
};


/**
 * @param {!proto.cluster_controller.CreateJoinTokenRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.CreateJoinTokenResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.createJoinToken =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/CreateJoinToken',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_CreateJoinToken);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.RequestJoinRequest,
 *   !proto.cluster_controller.RequestJoinResponse>}
 */
const methodDescriptor_ClusterControllerService_RequestJoin = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/RequestJoin',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.RequestJoinRequest,
  proto.cluster_controller.RequestJoinResponse,
  /**
   * @param {!proto.cluster_controller.RequestJoinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.RequestJoinResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.RequestJoinRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.RequestJoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.RequestJoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.requestJoin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RequestJoin',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RequestJoin,
      callback);
};


/**
 * @param {!proto.cluster_controller.RequestJoinRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.RequestJoinResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.requestJoin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RequestJoin',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RequestJoin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ListJoinRequestsRequest,
 *   !proto.cluster_controller.ListJoinRequestsResponse>}
 */
const methodDescriptor_ClusterControllerService_ListJoinRequests = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ListJoinRequests',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ListJoinRequestsRequest,
  proto.cluster_controller.ListJoinRequestsResponse,
  /**
   * @param {!proto.cluster_controller.ListJoinRequestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ListJoinRequestsResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ListJoinRequestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ListJoinRequestsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ListJoinRequestsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.listJoinRequests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ListJoinRequests',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ListJoinRequests,
      callback);
};


/**
 * @param {!proto.cluster_controller.ListJoinRequestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ListJoinRequestsResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.listJoinRequests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ListJoinRequests',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ListJoinRequests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ApproveJoinRequest,
 *   !proto.cluster_controller.ApproveJoinResponse>}
 */
const methodDescriptor_ClusterControllerService_ApproveJoin = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ApproveJoin',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ApproveJoinRequest,
  proto.cluster_controller.ApproveJoinResponse,
  /**
   * @param {!proto.cluster_controller.ApproveJoinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ApproveJoinResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ApproveJoinRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ApproveJoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ApproveJoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.approveJoin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ApproveJoin',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ApproveJoin,
      callback);
};


/**
 * @param {!proto.cluster_controller.ApproveJoinRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ApproveJoinResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.approveJoin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ApproveJoin',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ApproveJoin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.RejectJoinRequest,
 *   !proto.cluster_controller.RejectJoinResponse>}
 */
const methodDescriptor_ClusterControllerService_RejectJoin = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/RejectJoin',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.RejectJoinRequest,
  proto.cluster_controller.RejectJoinResponse,
  /**
   * @param {!proto.cluster_controller.RejectJoinRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.RejectJoinResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.RejectJoinRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.RejectJoinResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.RejectJoinResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.rejectJoin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RejectJoin',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RejectJoin,
      callback);
};


/**
 * @param {!proto.cluster_controller.RejectJoinRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.RejectJoinResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.rejectJoin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RejectJoin',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RejectJoin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ListNodesRequest,
 *   !proto.cluster_controller.ListNodesResponse>}
 */
const methodDescriptor_ClusterControllerService_ListNodes = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ListNodes',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ListNodesRequest,
  proto.cluster_controller.ListNodesResponse,
  /**
   * @param {!proto.cluster_controller.ListNodesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ListNodesResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ListNodesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ListNodesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ListNodesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.listNodes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ListNodes',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ListNodes,
      callback);
};


/**
 * @param {!proto.cluster_controller.ListNodesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ListNodesResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.listNodes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ListNodes',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ListNodes);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.SetNodeProfilesRequest,
 *   !proto.cluster_controller.SetNodeProfilesResponse>}
 */
const methodDescriptor_ClusterControllerService_SetNodeProfiles = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/SetNodeProfiles',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.SetNodeProfilesRequest,
  proto.cluster_controller.SetNodeProfilesResponse,
  /**
   * @param {!proto.cluster_controller.SetNodeProfilesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.SetNodeProfilesResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.SetNodeProfilesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.SetNodeProfilesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.SetNodeProfilesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.setNodeProfiles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/SetNodeProfiles',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_SetNodeProfiles,
      callback);
};


/**
 * @param {!proto.cluster_controller.SetNodeProfilesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.SetNodeProfilesResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.setNodeProfiles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/SetNodeProfiles',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_SetNodeProfiles);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.RemoveNodeRequest,
 *   !proto.cluster_controller.RemoveNodeResponse>}
 */
const methodDescriptor_ClusterControllerService_RemoveNode = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/RemoveNode',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.RemoveNodeRequest,
  proto.cluster_controller.RemoveNodeResponse,
  /**
   * @param {!proto.cluster_controller.RemoveNodeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.RemoveNodeResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.RemoveNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.RemoveNodeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.RemoveNodeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.removeNode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RemoveNode',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RemoveNode,
      callback);
};


/**
 * @param {!proto.cluster_controller.RemoveNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.RemoveNodeResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.removeNode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RemoveNode',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RemoveNode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.GetClusterHealthRequest,
 *   !proto.cluster_controller.GetClusterHealthResponse>}
 */
const methodDescriptor_ClusterControllerService_GetClusterHealth = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetClusterHealth',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.GetClusterHealthRequest,
  proto.cluster_controller.GetClusterHealthResponse,
  /**
   * @param {!proto.cluster_controller.GetClusterHealthRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.GetClusterHealthResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.GetClusterHealthRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.GetClusterHealthResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.GetClusterHealthResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getClusterHealth =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetClusterHealth',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetClusterHealth,
      callback);
};


/**
 * @param {!proto.cluster_controller.GetClusterHealthRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.GetClusterHealthResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getClusterHealth =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetClusterHealth',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetClusterHealth);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.GetNodePlanRequest,
 *   !proto.cluster_controller.GetNodePlanResponse>}
 */
const methodDescriptor_ClusterControllerService_GetNodePlan = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetNodePlan',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.GetNodePlanRequest,
  proto.cluster_controller.GetNodePlanResponse,
  /**
   * @param {!proto.cluster_controller.GetNodePlanRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.GetNodePlanResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.GetNodePlanRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.GetNodePlanResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.GetNodePlanResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getNodePlan =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetNodePlan',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetNodePlan,
      callback);
};


/**
 * @param {!proto.cluster_controller.GetNodePlanRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.GetNodePlanResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getNodePlan =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetNodePlan',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetNodePlan);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.GetNodePlanV1Request,
 *   !proto.cluster_controller.GetNodePlanV1Response>}
 */
const methodDescriptor_ClusterControllerService_GetNodePlanV1 = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetNodePlanV1',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.GetNodePlanV1Request,
  proto.cluster_controller.GetNodePlanV1Response,
  /**
   * @param {!proto.cluster_controller.GetNodePlanV1Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.GetNodePlanV1Response.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.GetNodePlanV1Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.GetNodePlanV1Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.GetNodePlanV1Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getNodePlanV1 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetNodePlanV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetNodePlanV1,
      callback);
};


/**
 * @param {!proto.cluster_controller.GetNodePlanV1Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.GetNodePlanV1Response>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getNodePlanV1 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetNodePlanV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetNodePlanV1);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ReconcileNodeV1Request,
 *   !proto.cluster_controller.ReconcileNodeV1Response>}
 */
const methodDescriptor_ClusterControllerService_ReconcileNodeV1 = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ReconcileNodeV1',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ReconcileNodeV1Request,
  proto.cluster_controller.ReconcileNodeV1Response,
  /**
   * @param {!proto.cluster_controller.ReconcileNodeV1Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ReconcileNodeV1Response.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ReconcileNodeV1Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ReconcileNodeV1Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ReconcileNodeV1Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.reconcileNodeV1 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ReconcileNodeV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ReconcileNodeV1,
      callback);
};


/**
 * @param {!proto.cluster_controller.ReconcileNodeV1Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ReconcileNodeV1Response>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.reconcileNodeV1 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ReconcileNodeV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ReconcileNodeV1);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.WatchNodePlanStatusV1Request,
 *   !proto.globular.plan.v1.NodePlanStatus>}
 */
const methodDescriptor_ClusterControllerService_WatchNodePlanStatusV1 = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/WatchNodePlanStatusV1',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cluster_controller.WatchNodePlanStatusV1Request,
  plan_pb.NodePlanStatus,
  /**
   * @param {!proto.cluster_controller.WatchNodePlanStatusV1Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  plan_pb.NodePlanStatus.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.WatchNodePlanStatusV1Request} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.globular.plan.v1.NodePlanStatus>}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.watchNodePlanStatusV1 =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cluster_controller.ClusterControllerService/WatchNodePlanStatusV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_WatchNodePlanStatusV1);
};


/**
 * @param {!proto.cluster_controller.WatchNodePlanStatusV1Request} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.globular.plan.v1.NodePlanStatus>}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.watchNodePlanStatusV1 =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cluster_controller.ClusterControllerService/WatchNodePlanStatusV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_WatchNodePlanStatusV1);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.UpdateClusterNetworkRequest,
 *   !proto.cluster_controller.UpdateClusterNetworkResponse>}
 */
const methodDescriptor_ClusterControllerService_UpdateClusterNetwork = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/UpdateClusterNetwork',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.UpdateClusterNetworkRequest,
  proto.cluster_controller.UpdateClusterNetworkResponse,
  /**
   * @param {!proto.cluster_controller.UpdateClusterNetworkRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.UpdateClusterNetworkResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.UpdateClusterNetworkRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.UpdateClusterNetworkResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.UpdateClusterNetworkResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.updateClusterNetwork =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/UpdateClusterNetwork',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_UpdateClusterNetwork,
      callback);
};


/**
 * @param {!proto.cluster_controller.UpdateClusterNetworkRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.UpdateClusterNetworkResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.updateClusterNetwork =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/UpdateClusterNetwork',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_UpdateClusterNetwork);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ApplyNodePlanRequest,
 *   !proto.cluster_controller.ApplyNodePlanResponse>}
 */
const methodDescriptor_ClusterControllerService_ApplyNodePlan = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ApplyNodePlan',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ApplyNodePlanRequest,
  proto.cluster_controller.ApplyNodePlanResponse,
  /**
   * @param {!proto.cluster_controller.ApplyNodePlanRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ApplyNodePlanResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ApplyNodePlanRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ApplyNodePlanResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ApplyNodePlanResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.applyNodePlan =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ApplyNodePlan',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ApplyNodePlan,
      callback);
};


/**
 * @param {!proto.cluster_controller.ApplyNodePlanRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ApplyNodePlanResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.applyNodePlan =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ApplyNodePlan',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ApplyNodePlan);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ApplyNodePlanV1Request,
 *   !proto.cluster_controller.ApplyNodePlanV1Response>}
 */
const methodDescriptor_ClusterControllerService_ApplyNodePlanV1 = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ApplyNodePlanV1',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ApplyNodePlanV1Request,
  proto.cluster_controller.ApplyNodePlanV1Response,
  /**
   * @param {!proto.cluster_controller.ApplyNodePlanV1Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ApplyNodePlanV1Response.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ApplyNodePlanV1Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ApplyNodePlanV1Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ApplyNodePlanV1Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.applyNodePlanV1 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ApplyNodePlanV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ApplyNodePlanV1,
      callback);
};


/**
 * @param {!proto.cluster_controller.ApplyNodePlanV1Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ApplyNodePlanV1Response>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.applyNodePlanV1 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ApplyNodePlanV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ApplyNodePlanV1);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ReportNodeStatusRequest,
 *   !proto.cluster_controller.ReportNodeStatusResponse>}
 */
const methodDescriptor_ClusterControllerService_ReportNodeStatus = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ReportNodeStatus',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ReportNodeStatusRequest,
  proto.cluster_controller.ReportNodeStatusResponse,
  /**
   * @param {!proto.cluster_controller.ReportNodeStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ReportNodeStatusResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ReportNodeStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ReportNodeStatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ReportNodeStatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.reportNodeStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ReportNodeStatus',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ReportNodeStatus,
      callback);
};


/**
 * @param {!proto.cluster_controller.ReportNodeStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ReportNodeStatusResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.reportNodeStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ReportNodeStatus',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ReportNodeStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.GetJoinRequestStatusRequest,
 *   !proto.cluster_controller.GetJoinRequestStatusResponse>}
 */
const methodDescriptor_ClusterControllerService_GetJoinRequestStatus = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetJoinRequestStatus',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.GetJoinRequestStatusRequest,
  proto.cluster_controller.GetJoinRequestStatusResponse,
  /**
   * @param {!proto.cluster_controller.GetJoinRequestStatusRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.GetJoinRequestStatusResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.GetJoinRequestStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.GetJoinRequestStatusResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.GetJoinRequestStatusResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getJoinRequestStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetJoinRequestStatus',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetJoinRequestStatus,
      callback);
};


/**
 * @param {!proto.cluster_controller.GetJoinRequestStatusRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.GetJoinRequestStatusResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getJoinRequestStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetJoinRequestStatus',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetJoinRequestStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.UpgradeGlobularRequest,
 *   !proto.cluster_controller.UpgradeGlobularResponse>}
 */
const methodDescriptor_ClusterControllerService_UpgradeGlobular = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/UpgradeGlobular',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.UpgradeGlobularRequest,
  proto.cluster_controller.UpgradeGlobularResponse,
  /**
   * @param {!proto.cluster_controller.UpgradeGlobularRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.UpgradeGlobularResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.UpgradeGlobularRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.UpgradeGlobularResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.UpgradeGlobularResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.upgradeGlobular =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/UpgradeGlobular',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_UpgradeGlobular,
      callback);
};


/**
 * @param {!proto.cluster_controller.UpgradeGlobularRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.UpgradeGlobularResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.upgradeGlobular =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/UpgradeGlobular',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_UpgradeGlobular);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.CompleteOperationRequest,
 *   !proto.cluster_controller.CompleteOperationResponse>}
 */
const methodDescriptor_ClusterControllerService_CompleteOperation = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/CompleteOperation',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.CompleteOperationRequest,
  proto.cluster_controller.CompleteOperationResponse,
  /**
   * @param {!proto.cluster_controller.CompleteOperationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.CompleteOperationResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.CompleteOperationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.CompleteOperationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.CompleteOperationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.completeOperation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/CompleteOperation',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_CompleteOperation,
      callback);
};


/**
 * @param {!proto.cluster_controller.CompleteOperationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.CompleteOperationResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.completeOperation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/CompleteOperation',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_CompleteOperation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.WatchOperationsRequest,
 *   !proto.cluster_controller.OperationEvent>}
 */
const methodDescriptor_ClusterControllerService_WatchOperations = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/WatchOperations',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.cluster_controller.WatchOperationsRequest,
  proto.cluster_controller.OperationEvent,
  /**
   * @param {!proto.cluster_controller.WatchOperationsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.OperationEvent.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.WatchOperationsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.OperationEvent>}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.watchOperations =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cluster_controller.ClusterControllerService/WatchOperations',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_WatchOperations);
};


/**
 * @param {!proto.cluster_controller.WatchOperationsRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.OperationEvent>}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.watchOperations =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/cluster_controller.ClusterControllerService/WatchOperations',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_WatchOperations);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.GetClusterHealthV1Request,
 *   !proto.cluster_controller.GetClusterHealthV1Response>}
 */
const methodDescriptor_ClusterControllerService_GetClusterHealthV1 = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetClusterHealthV1',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.GetClusterHealthV1Request,
  proto.cluster_controller.GetClusterHealthV1Response,
  /**
   * @param {!proto.cluster_controller.GetClusterHealthV1Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.GetClusterHealthV1Response.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.GetClusterHealthV1Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.GetClusterHealthV1Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.GetClusterHealthV1Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getClusterHealthV1 =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetClusterHealthV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetClusterHealthV1,
      callback);
};


/**
 * @param {!proto.cluster_controller.GetClusterHealthV1Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.GetClusterHealthV1Response>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getClusterHealthV1 =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetClusterHealthV1',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetClusterHealthV1);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.PreviewNodeProfilesRequest,
 *   !proto.cluster_controller.PreviewNodeProfilesResponse>}
 */
const methodDescriptor_ClusterControllerService_PreviewNodeProfiles = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/PreviewNodeProfiles',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.PreviewNodeProfilesRequest,
  proto.cluster_controller.PreviewNodeProfilesResponse,
  /**
   * @param {!proto.cluster_controller.PreviewNodeProfilesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.PreviewNodeProfilesResponse.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.PreviewNodeProfilesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.PreviewNodeProfilesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.PreviewNodeProfilesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.previewNodeProfiles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/PreviewNodeProfiles',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_PreviewNodeProfiles,
      callback);
};


/**
 * @param {!proto.cluster_controller.PreviewNodeProfilesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.PreviewNodeProfilesResponse>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.previewNodeProfiles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/PreviewNodeProfiles',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_PreviewNodeProfiles);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.cluster_controller.DesiredState>}
 */
const methodDescriptor_ClusterControllerService_GetDesiredState = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/GetDesiredState',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.cluster_controller.DesiredState,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.DesiredState.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.DesiredState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.DesiredState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.getDesiredState =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetDesiredState',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetDesiredState,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.DesiredState>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.getDesiredState =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/GetDesiredState',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_GetDesiredState);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.UpsertDesiredServiceRequest,
 *   !proto.cluster_controller.DesiredState>}
 */
const methodDescriptor_ClusterControllerService_UpsertDesiredService = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/UpsertDesiredService',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.UpsertDesiredServiceRequest,
  proto.cluster_controller.DesiredState,
  /**
   * @param {!proto.cluster_controller.UpsertDesiredServiceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.DesiredState.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.UpsertDesiredServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.DesiredState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.DesiredState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.upsertDesiredService =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/UpsertDesiredService',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_UpsertDesiredService,
      callback);
};


/**
 * @param {!proto.cluster_controller.UpsertDesiredServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.DesiredState>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.upsertDesiredService =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/UpsertDesiredService',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_UpsertDesiredService);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.RemoveDesiredServiceRequest,
 *   !proto.cluster_controller.DesiredState>}
 */
const methodDescriptor_ClusterControllerService_RemoveDesiredService = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/RemoveDesiredService',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.RemoveDesiredServiceRequest,
  proto.cluster_controller.DesiredState,
  /**
   * @param {!proto.cluster_controller.RemoveDesiredServiceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.DesiredState.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.RemoveDesiredServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.DesiredState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.DesiredState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.removeDesiredService =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RemoveDesiredService',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RemoveDesiredService,
      callback);
};


/**
 * @param {!proto.cluster_controller.RemoveDesiredServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.DesiredState>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.removeDesiredService =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/RemoveDesiredService',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_RemoveDesiredService);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.SeedDesiredStateRequest,
 *   !proto.cluster_controller.DesiredState>}
 */
const methodDescriptor_ClusterControllerService_SeedDesiredState = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/SeedDesiredState',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.SeedDesiredStateRequest,
  proto.cluster_controller.DesiredState,
  /**
   * @param {!proto.cluster_controller.SeedDesiredStateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.DesiredState.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.SeedDesiredStateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.DesiredState)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.DesiredState>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.seedDesiredState =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/SeedDesiredState',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_SeedDesiredState,
      callback);
};


/**
 * @param {!proto.cluster_controller.SeedDesiredStateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.DesiredState>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.seedDesiredState =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/SeedDesiredState',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_SeedDesiredState);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.ValidateArtifactRequest,
 *   !proto.cluster_controller.ValidationReport>}
 */
const methodDescriptor_ClusterControllerService_ValidateArtifact = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/ValidateArtifact',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.ValidateArtifactRequest,
  proto.cluster_controller.ValidationReport,
  /**
   * @param {!proto.cluster_controller.ValidateArtifactRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.ValidationReport.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.ValidateArtifactRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.ValidationReport)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.ValidationReport>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.validateArtifact =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ValidateArtifact',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ValidateArtifact,
      callback);
};


/**
 * @param {!proto.cluster_controller.ValidateArtifactRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.ValidationReport>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.validateArtifact =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/ValidateArtifact',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_ValidateArtifact);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.cluster_controller.DesiredServicesDelta,
 *   !proto.cluster_controller.PlanPreview>}
 */
const methodDescriptor_ClusterControllerService_PreviewDesiredServices = new grpc.web.MethodDescriptor(
  '/cluster_controller.ClusterControllerService/PreviewDesiredServices',
  grpc.web.MethodType.UNARY,
  proto.cluster_controller.DesiredServicesDelta,
  proto.cluster_controller.PlanPreview,
  /**
   * @param {!proto.cluster_controller.DesiredServicesDelta} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.cluster_controller.PlanPreview.deserializeBinary
);


/**
 * @param {!proto.cluster_controller.DesiredServicesDelta} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.cluster_controller.PlanPreview)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.cluster_controller.PlanPreview>|undefined}
 *     The XHR Node Readable Stream
 */
proto.cluster_controller.ClusterControllerServiceClient.prototype.previewDesiredServices =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/PreviewDesiredServices',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_PreviewDesiredServices,
      callback);
};


/**
 * @param {!proto.cluster_controller.DesiredServicesDelta} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.cluster_controller.PlanPreview>}
 *     Promise that resolves to the response
 */
proto.cluster_controller.ClusterControllerServicePromiseClient.prototype.previewDesiredServices =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/cluster_controller.ClusterControllerService/PreviewDesiredServices',
      request,
      metadata || {},
      methodDescriptor_ClusterControllerService_PreviewDesiredServices);
};


module.exports = proto.cluster_controller;

