// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: workflow.proto

package workflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowService_StartRun_FullMethodName              = "/workflow.WorkflowService/StartRun"
	WorkflowService_UpdateRun_FullMethodName             = "/workflow.WorkflowService/UpdateRun"
	WorkflowService_FinishRun_FullMethodName             = "/workflow.WorkflowService/FinishRun"
	WorkflowService_RecordStep_FullMethodName            = "/workflow.WorkflowService/RecordStep"
	WorkflowService_UpdateStep_FullMethodName            = "/workflow.WorkflowService/UpdateStep"
	WorkflowService_FailStep_FullMethodName              = "/workflow.WorkflowService/FailStep"
	WorkflowService_AddArtifactRef_FullMethodName        = "/workflow.WorkflowService/AddArtifactRef"
	WorkflowService_AppendEvent_FullMethodName           = "/workflow.WorkflowService/AppendEvent"
	WorkflowService_GetRun_FullMethodName                = "/workflow.WorkflowService/GetRun"
	WorkflowService_ListRuns_FullMethodName              = "/workflow.WorkflowService/ListRuns"
	WorkflowService_GetRunEvents_FullMethodName          = "/workflow.WorkflowService/GetRunEvents"
	WorkflowService_GetCurrentRunsForNode_FullMethodName = "/workflow.WorkflowService/GetCurrentRunsForNode"
	WorkflowService_GetComponentHistory_FullMethodName   = "/workflow.WorkflowService/GetComponentHistory"
	WorkflowService_GetWorkflowGraph_FullMethodName      = "/workflow.WorkflowService/GetWorkflowGraph"
	WorkflowService_WatchRun_FullMethodName              = "/workflow.WorkflowService/WatchRun"
	WorkflowService_WatchNodeRuns_FullMethodName         = "/workflow.WorkflowService/WatchNodeRuns"
	WorkflowService_RetryRun_FullMethodName              = "/workflow.WorkflowService/RetryRun"
	WorkflowService_CancelRun_FullMethodName             = "/workflow.WorkflowService/CancelRun"
	WorkflowService_AcknowledgeRun_FullMethodName        = "/workflow.WorkflowService/AcknowledgeRun"
	WorkflowService_DiagnoseRun_FullMethodName           = "/workflow.WorkflowService/DiagnoseRun"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	// Write path — internal producers (controller, node-agent, installer)
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*WorkflowRun, error)
	UpdateRun(ctx context.Context, in *UpdateRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FinishRun(ctx context.Context, in *FinishRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecordStep(ctx context.Context, in *RecordStepRequest, opts ...grpc.CallOption) (*WorkflowStep, error)
	UpdateStep(ctx context.Context, in *UpdateStepRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FailStep(ctx context.Context, in *FailStepRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddArtifactRef(ctx context.Context, in *AddArtifactRefRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Read path — admin UI and AI
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*WorkflowRunDetail, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	GetRunEvents(ctx context.Context, in *GetRunEventsRequest, opts ...grpc.CallOption) (*GetRunEventsResponse, error)
	GetCurrentRunsForNode(ctx context.Context, in *GetCurrentRunsForNodeRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	GetComponentHistory(ctx context.Context, in *GetComponentHistoryRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	GetWorkflowGraph(ctx context.Context, in *GetWorkflowGraphRequest, opts ...grpc.CallOption) (*WorkflowGraph, error)
	// Streaming — live workflow monitor
	WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEventEnvelope], error)
	WatchNodeRuns(ctx context.Context, in *WatchNodeRunsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEventEnvelope], error)
	// Actions — operator controls
	RetryRun(ctx context.Context, in *RetryRunRequest, opts ...grpc.CallOption) (*WorkflowRun, error)
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AcknowledgeRun(ctx context.Context, in *AcknowledgeRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DiagnoseRun(ctx context.Context, in *DiagnoseRunRequest, opts ...grpc.CallOption) (*DiagnoseRunResponse, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*WorkflowRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRun)
	err := c.cc.Invoke(ctx, WorkflowService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UpdateRun(ctx context.Context, in *UpdateRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_UpdateRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) FinishRun(ctx context.Context, in *FinishRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_FinishRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RecordStep(ctx context.Context, in *RecordStepRequest, opts ...grpc.CallOption) (*WorkflowStep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowStep)
	err := c.cc.Invoke(ctx, WorkflowService_RecordStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) UpdateStep(ctx context.Context, in *UpdateStepRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_UpdateStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) FailStep(ctx context.Context, in *FailStepRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_FailStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) AddArtifactRef(ctx context.Context, in *AddArtifactRefRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_AddArtifactRef_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) AppendEvent(ctx context.Context, in *AppendEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_AppendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*WorkflowRunDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRunDetail)
	err := c.cc.Invoke(ctx, WorkflowService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetRunEvents(ctx context.Context, in *GetRunEventsRequest, opts ...grpc.CallOption) (*GetRunEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunEventsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetRunEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetCurrentRunsForNode(ctx context.Context, in *GetCurrentRunsForNodeRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetCurrentRunsForNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetComponentHistory(ctx context.Context, in *GetComponentHistoryRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetComponentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetWorkflowGraph(ctx context.Context, in *GetWorkflowGraphRequest, opts ...grpc.CallOption) (*WorkflowGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowGraph)
	err := c.cc.Invoke(ctx, WorkflowService_GetWorkflowGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowService_ServiceDesc.Streams[0], WorkflowService_WatchRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRunRequest, WorkflowEventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowService_WatchRunClient = grpc.ServerStreamingClient[WorkflowEventEnvelope]

func (c *workflowServiceClient) WatchNodeRuns(ctx context.Context, in *WatchNodeRunsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEventEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowService_ServiceDesc.Streams[1], WorkflowService_WatchNodeRuns_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchNodeRunsRequest, WorkflowEventEnvelope]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowService_WatchNodeRunsClient = grpc.ServerStreamingClient[WorkflowEventEnvelope]

func (c *workflowServiceClient) RetryRun(ctx context.Context, in *RetryRunRequest, opts ...grpc.CallOption) (*WorkflowRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRun)
	err := c.cc.Invoke(ctx, WorkflowService_RetryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) AcknowledgeRun(ctx context.Context, in *AcknowledgeRunRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WorkflowService_AcknowledgeRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DiagnoseRun(ctx context.Context, in *DiagnoseRunRequest, opts ...grpc.CallOption) (*DiagnoseRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnoseRunResponse)
	err := c.cc.Invoke(ctx, WorkflowService_DiagnoseRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
type WorkflowServiceServer interface {
	// Write path — internal producers (controller, node-agent, installer)
	StartRun(context.Context, *StartRunRequest) (*WorkflowRun, error)
	UpdateRun(context.Context, *UpdateRunRequest) (*emptypb.Empty, error)
	FinishRun(context.Context, *FinishRunRequest) (*emptypb.Empty, error)
	RecordStep(context.Context, *RecordStepRequest) (*WorkflowStep, error)
	UpdateStep(context.Context, *UpdateStepRequest) (*emptypb.Empty, error)
	FailStep(context.Context, *FailStepRequest) (*emptypb.Empty, error)
	AddArtifactRef(context.Context, *AddArtifactRefRequest) (*emptypb.Empty, error)
	AppendEvent(context.Context, *AppendEventRequest) (*emptypb.Empty, error)
	// Read path — admin UI and AI
	GetRun(context.Context, *GetRunRequest) (*WorkflowRunDetail, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	GetRunEvents(context.Context, *GetRunEventsRequest) (*GetRunEventsResponse, error)
	GetCurrentRunsForNode(context.Context, *GetCurrentRunsForNodeRequest) (*ListRunsResponse, error)
	GetComponentHistory(context.Context, *GetComponentHistoryRequest) (*ListRunsResponse, error)
	GetWorkflowGraph(context.Context, *GetWorkflowGraphRequest) (*WorkflowGraph, error)
	// Streaming — live workflow monitor
	WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[WorkflowEventEnvelope]) error
	WatchNodeRuns(*WatchNodeRunsRequest, grpc.ServerStreamingServer[WorkflowEventEnvelope]) error
	// Actions — operator controls
	RetryRun(context.Context, *RetryRunRequest) (*WorkflowRun, error)
	CancelRun(context.Context, *CancelRunRequest) (*emptypb.Empty, error)
	AcknowledgeRun(context.Context, *AcknowledgeRunRequest) (*emptypb.Empty, error)
	DiagnoseRun(context.Context, *DiagnoseRunRequest) (*DiagnoseRunResponse, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) StartRun(context.Context, *StartRunRequest) (*WorkflowRun, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedWorkflowServiceServer) UpdateRun(context.Context, *UpdateRunRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRun not implemented")
}
func (UnimplementedWorkflowServiceServer) FinishRun(context.Context, *FinishRunRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FinishRun not implemented")
}
func (UnimplementedWorkflowServiceServer) RecordStep(context.Context, *RecordStepRequest) (*WorkflowStep, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordStep not implemented")
}
func (UnimplementedWorkflowServiceServer) UpdateStep(context.Context, *UpdateStepRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStep not implemented")
}
func (UnimplementedWorkflowServiceServer) FailStep(context.Context, *FailStepRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FailStep not implemented")
}
func (UnimplementedWorkflowServiceServer) AddArtifactRef(context.Context, *AddArtifactRefRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddArtifactRef not implemented")
}
func (UnimplementedWorkflowServiceServer) AppendEvent(context.Context, *AppendEventRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AppendEvent not implemented")
}
func (UnimplementedWorkflowServiceServer) GetRun(context.Context, *GetRunRequest) (*WorkflowRunDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedWorkflowServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedWorkflowServiceServer) GetRunEvents(context.Context, *GetRunEventsRequest) (*GetRunEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunEvents not implemented")
}
func (UnimplementedWorkflowServiceServer) GetCurrentRunsForNode(context.Context, *GetCurrentRunsForNodeRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentRunsForNode not implemented")
}
func (UnimplementedWorkflowServiceServer) GetComponentHistory(context.Context, *GetComponentHistoryRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComponentHistory not implemented")
}
func (UnimplementedWorkflowServiceServer) GetWorkflowGraph(context.Context, *GetWorkflowGraphRequest) (*WorkflowGraph, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowGraph not implemented")
}
func (UnimplementedWorkflowServiceServer) WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[WorkflowEventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method WatchRun not implemented")
}
func (UnimplementedWorkflowServiceServer) WatchNodeRuns(*WatchNodeRunsRequest, grpc.ServerStreamingServer[WorkflowEventEnvelope]) error {
	return status.Error(codes.Unimplemented, "method WatchNodeRuns not implemented")
}
func (UnimplementedWorkflowServiceServer) RetryRun(context.Context, *RetryRunRequest) (*WorkflowRun, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryRun not implemented")
}
func (UnimplementedWorkflowServiceServer) CancelRun(context.Context, *CancelRunRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedWorkflowServiceServer) AcknowledgeRun(context.Context, *AcknowledgeRunRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeRun not implemented")
}
func (UnimplementedWorkflowServiceServer) DiagnoseRun(context.Context, *DiagnoseRunRequest) (*DiagnoseRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiagnoseRun not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UpdateRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UpdateRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_UpdateRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UpdateRun(ctx, req.(*UpdateRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_FinishRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).FinishRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_FinishRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).FinishRun(ctx, req.(*FinishRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RecordStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RecordStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RecordStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RecordStep(ctx, req.(*RecordStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_UpdateStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).UpdateStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_UpdateStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).UpdateStep(ctx, req.(*UpdateStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_FailStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).FailStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_FailStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).FailStep(ctx, req.(*FailStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_AddArtifactRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddArtifactRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).AddArtifactRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_AddArtifactRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).AddArtifactRef(ctx, req.(*AddArtifactRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_AppendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).AppendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_AppendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).AppendEvent(ctx, req.(*AppendEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetRunEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetRunEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetRunEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetRunEvents(ctx, req.(*GetRunEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetCurrentRunsForNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRunsForNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetCurrentRunsForNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetCurrentRunsForNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetCurrentRunsForNode(ctx, req.(*GetCurrentRunsForNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetComponentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComponentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetComponentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetComponentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetComponentHistory(ctx, req.(*GetComponentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetWorkflowGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetWorkflowGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetWorkflowGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetWorkflowGraph(ctx, req.(*GetWorkflowGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_WatchRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).WatchRun(m, &grpc.GenericServerStream[WatchRunRequest, WorkflowEventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowService_WatchRunServer = grpc.ServerStreamingServer[WorkflowEventEnvelope]

func _WorkflowService_WatchNodeRuns_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchNodeRunsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowServiceServer).WatchNodeRuns(m, &grpc.GenericServerStream[WatchNodeRunsRequest, WorkflowEventEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowService_WatchNodeRunsServer = grpc.ServerStreamingServer[WorkflowEventEnvelope]

func _WorkflowService_RetryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RetryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RetryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RetryRun(ctx, req.(*RetryRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_AcknowledgeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).AcknowledgeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_AcknowledgeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).AcknowledgeRun(ctx, req.(*AcknowledgeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DiagnoseRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnoseRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DiagnoseRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DiagnoseRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DiagnoseRun(ctx, req.(*DiagnoseRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _WorkflowService_StartRun_Handler,
		},
		{
			MethodName: "UpdateRun",
			Handler:    _WorkflowService_UpdateRun_Handler,
		},
		{
			MethodName: "FinishRun",
			Handler:    _WorkflowService_FinishRun_Handler,
		},
		{
			MethodName: "RecordStep",
			Handler:    _WorkflowService_RecordStep_Handler,
		},
		{
			MethodName: "UpdateStep",
			Handler:    _WorkflowService_UpdateStep_Handler,
		},
		{
			MethodName: "FailStep",
			Handler:    _WorkflowService_FailStep_Handler,
		},
		{
			MethodName: "AddArtifactRef",
			Handler:    _WorkflowService_AddArtifactRef_Handler,
		},
		{
			MethodName: "AppendEvent",
			Handler:    _WorkflowService_AppendEvent_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _WorkflowService_GetRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _WorkflowService_ListRuns_Handler,
		},
		{
			MethodName: "GetRunEvents",
			Handler:    _WorkflowService_GetRunEvents_Handler,
		},
		{
			MethodName: "GetCurrentRunsForNode",
			Handler:    _WorkflowService_GetCurrentRunsForNode_Handler,
		},
		{
			MethodName: "GetComponentHistory",
			Handler:    _WorkflowService_GetComponentHistory_Handler,
		},
		{
			MethodName: "GetWorkflowGraph",
			Handler:    _WorkflowService_GetWorkflowGraph_Handler,
		},
		{
			MethodName: "RetryRun",
			Handler:    _WorkflowService_RetryRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _WorkflowService_CancelRun_Handler,
		},
		{
			MethodName: "AcknowledgeRun",
			Handler:    _WorkflowService_AcknowledgeRun_Handler,
		},
		{
			MethodName: "DiagnoseRun",
			Handler:    _WorkflowService_DiagnoseRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRun",
			Handler:       _WorkflowService_WatchRun_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchNodeRuns",
			Handler:       _WorkflowService_WatchNodeRuns_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "workflow.proto",
}
