// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: ai_router.proto

package ai_routerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiRouterService_GetRoutingPolicy_FullMethodName          = "/ai_router.AiRouterService/GetRoutingPolicy"
	AiRouterService_GetStatus_FullMethodName                 = "/ai_router.AiRouterService/GetStatus"
	AiRouterService_SetMode_FullMethodName                   = "/ai_router.AiRouterService/SetMode"
	AiRouterService_GetServiceClassifications_FullMethodName = "/ai_router.AiRouterService/GetServiceClassifications"
	AiRouterService_Stop_FullMethodName                      = "/ai_router.AiRouterService/Stop"
)

// AiRouterServiceClient is the client API for AiRouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AiRouterService is a control-plane routing policy engine that computes
// dynamic endpoint weights, circuit breaker overrides, and drain strategies
// based on real-time metrics, anomaly signals, and historical patterns.
//
// It does NOT sit in the request path. It shapes the xDS configuration
// that Envoy uses to distribute traffic.
type AiRouterServiceClient interface {
	// GetRoutingPolicy returns the current routing policy for all or one service.
	// Called by the xDS watcher every sync cycle (~5 seconds).
	// Returns empty/neutral policy when the router has no opinion.
	GetRoutingPolicy(ctx context.Context, in *GetRoutingPolicyRequest, opts ...grpc.CallOption) (*GetRoutingPolicyResponse, error)
	// GetStatus returns operational status: mode, uptime, policies served, etc.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// SetMode switches between neutral, observe, and active modes.
	SetMode(ctx context.Context, in *SetModeRequest, opts ...grpc.CallOption) (*SetModeResponse, error)
	// GetServiceClassifications returns the current service class map.
	GetServiceClassifications(ctx context.Context, in *GetServiceClassificationsRequest, opts ...grpc.CallOption) (*GetServiceClassificationsResponse, error)
	// Stop gracefully shuts down the router.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type aiRouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiRouterServiceClient(cc grpc.ClientConnInterface) AiRouterServiceClient {
	return &aiRouterServiceClient{cc}
}

func (c *aiRouterServiceClient) GetRoutingPolicy(ctx context.Context, in *GetRoutingPolicyRequest, opts ...grpc.CallOption) (*GetRoutingPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingPolicyResponse)
	err := c.cc.Invoke(ctx, AiRouterService_GetRoutingPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiRouterServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AiRouterService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiRouterServiceClient) SetMode(ctx context.Context, in *SetModeRequest, opts ...grpc.CallOption) (*SetModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetModeResponse)
	err := c.cc.Invoke(ctx, AiRouterService_SetMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiRouterServiceClient) GetServiceClassifications(ctx context.Context, in *GetServiceClassificationsRequest, opts ...grpc.CallOption) (*GetServiceClassificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceClassificationsResponse)
	err := c.cc.Invoke(ctx, AiRouterService_GetServiceClassifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiRouterServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, AiRouterService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiRouterServiceServer is the server API for AiRouterService service.
// All implementations must embed UnimplementedAiRouterServiceServer
// for forward compatibility.
//
// AiRouterService is a control-plane routing policy engine that computes
// dynamic endpoint weights, circuit breaker overrides, and drain strategies
// based on real-time metrics, anomaly signals, and historical patterns.
//
// It does NOT sit in the request path. It shapes the xDS configuration
// that Envoy uses to distribute traffic.
type AiRouterServiceServer interface {
	// GetRoutingPolicy returns the current routing policy for all or one service.
	// Called by the xDS watcher every sync cycle (~5 seconds).
	// Returns empty/neutral policy when the router has no opinion.
	GetRoutingPolicy(context.Context, *GetRoutingPolicyRequest) (*GetRoutingPolicyResponse, error)
	// GetStatus returns operational status: mode, uptime, policies served, etc.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// SetMode switches between neutral, observe, and active modes.
	SetMode(context.Context, *SetModeRequest) (*SetModeResponse, error)
	// GetServiceClassifications returns the current service class map.
	GetServiceClassifications(context.Context, *GetServiceClassificationsRequest) (*GetServiceClassificationsResponse, error)
	// Stop gracefully shuts down the router.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedAiRouterServiceServer()
}

// UnimplementedAiRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiRouterServiceServer struct{}

func (UnimplementedAiRouterServiceServer) GetRoutingPolicy(context.Context, *GetRoutingPolicyRequest) (*GetRoutingPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingPolicy not implemented")
}
func (UnimplementedAiRouterServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAiRouterServiceServer) SetMode(context.Context, *SetModeRequest) (*SetModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMode not implemented")
}
func (UnimplementedAiRouterServiceServer) GetServiceClassifications(context.Context, *GetServiceClassificationsRequest) (*GetServiceClassificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceClassifications not implemented")
}
func (UnimplementedAiRouterServiceServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedAiRouterServiceServer) mustEmbedUnimplementedAiRouterServiceServer() {}
func (UnimplementedAiRouterServiceServer) testEmbeddedByValue()                         {}

// UnsafeAiRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiRouterServiceServer will
// result in compilation errors.
type UnsafeAiRouterServiceServer interface {
	mustEmbedUnimplementedAiRouterServiceServer()
}

func RegisterAiRouterServiceServer(s grpc.ServiceRegistrar, srv AiRouterServiceServer) {
	// If the following call panics, it indicates UnimplementedAiRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiRouterService_ServiceDesc, srv)
}

func _AiRouterService_GetRoutingPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiRouterServiceServer).GetRoutingPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiRouterService_GetRoutingPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiRouterServiceServer).GetRoutingPolicy(ctx, req.(*GetRoutingPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiRouterService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiRouterServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiRouterService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiRouterServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiRouterService_SetMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiRouterServiceServer).SetMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiRouterService_SetMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiRouterServiceServer).SetMode(ctx, req.(*SetModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiRouterService_GetServiceClassifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceClassificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiRouterServiceServer).GetServiceClassifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiRouterService_GetServiceClassifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiRouterServiceServer).GetServiceClassifications(ctx, req.(*GetServiceClassificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiRouterService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiRouterServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiRouterService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiRouterServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiRouterService_ServiceDesc is the grpc.ServiceDesc for AiRouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiRouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_router.AiRouterService",
	HandlerType: (*AiRouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoutingPolicy",
			Handler:    _AiRouterService_GetRoutingPolicy_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AiRouterService_GetStatus_Handler,
		},
		{
			MethodName: "SetMode",
			Handler:    _AiRouterService_SetMode_Handler,
		},
		{
			MethodName: "GetServiceClassifications",
			Handler:    _AiRouterService_GetServiceClassifications_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _AiRouterService_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_router.proto",
}
